-- ============================================
-- Seed: Bairros de Manaus (63 bairros oficiais)
-- Cadê o Lixeiro? v2.0
-- ============================================
-- Fonte: SEMURB / Prefeitura de Manaus
-- Nota: Geometrias (polígonos) serão adicionadas em seed futuro
-- ============================================

INSERT INTO public.bairros (nome) VALUES
    ('Adrianopolis'),
    ('Aleixo'),
    ('Alvorada'),
    ('Armando Mendes'),
    ('Betania'),
    ('Cachoeirinha'),
    ('Centro'),
    ('Chapada'),
    ('Cidade de Deus'),
    ('Cidade Nova'),
    ('Colonia Antonio Aleixo'),
    ('Colonia Oliveira Machado'),
    ('Colonia Santo Antonio'),
    ('Colonia Terra Nova'),
    ('Compensa'),
    ('Coroado'),
    ('Crespo'),
    ('Da Paz'),
    ('Distrito Industrial I'),
    ('Distrito Industrial II'),
    ('Dom Pedro'),
    ('Educandos'),
    ('Flores'),
    ('Gloria'),
    ('Graca'),
    ('Japiim'),
    ('Jorge Teixeira'),
    ('Lago Azul'),
    ('Lirio do Vale'),
    ('Mauazinho'),
    ('Monte das Oliveiras'),
    ('Morro da Liberdade'),
    ('Nossa Senhora Aparecida'),
    ('Nossa Senhora das Gracas'),
    ('Nova Cidade'),
    ('Nova Esperanca'),
    ('Novo Aleixo'),
    ('Novo Israel'),
    ('Parque 10 de Novembro'),
    ('Petropolis'),
    ('Planalto'),
    ('Ponta Negra'),
    ('Praca 14 de Janeiro'),
    ('Presidente Vargas'),
    ('Puraquequara'),
    ('Raiz'),
    ('Redencao'),
    ('Remanso'),
    ('Santa Etelvina'),
    ('Santa Luzia'),
    ('Santo Agostinho'),
    ('Santo Antonio'),
    ('Sao Francisco'),
    ('Sao Geraldo'),
    ('Sao Jorge'),
    ('Sao Jose Operario'),
    ('Sao Lazaro'),
    ('Sao Raimundo'),
    ('Taruma'),
    ('Taruma-Acu'),
    ('Tancredo Neves'),
    ('Vila Buriti'),
    ('Zumbi dos Palmares')
ON CONFLICT (nome) DO NOTHING;
