# Generated by Django 5.1.3 on 2024-11-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_route_routelocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='truck_id',
            new_name='truck',
        ),
        migrations.AddField(
            model_name='route',
            name='end_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='routelocation',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trucklocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trucklocation',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='routelocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routelocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
