# Generated by Django 5.1.3 on 2024-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_discardlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discardlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude do local de descarte', max_digits=100),
        ),
        migrations.AlterField(
            model_name='discardlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude do local de descarte', max_digits=100),
        ),
    ]
