# Generated by Django 5.1.3 on 2024-12-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_alter_discardlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discardlocation',
            name='latitude',
            field=models.CharField(help_text='Latitude do local de descarte', max_length=100),
        ),
        migrations.AlterField(
            model_name='discardlocation',
            name='longitude',
            field=models.CharField(help_text='Longitude do local de descarte', max_length=100),
        ),
    ]
